// Mock AI Service since we don't have a real API key provided for security reasons.
// In a real application, we would use axios to call the OpenAI API.
import axios from 'axios';

const DELAY_MS = 1500; // Simulate network delay

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export const aiService = {
  generateSummary: async (topicTitle) => {
    await sleep(DELAY_MS);
    return `Here is an AI-generated summary for **${topicTitle}**. \n\nThis robust topic encompasses various fundamental concepts crucial for deep understanding. Typically, students find the transition from basic to advanced theories in ${topicTitle} challenging but rewarding. Remember to focus on the core principles.\n\n*Generated by mock GPT-4o.*`;
  },
  
  generatePracticeQuestions: async (topicTitle) => {
    await sleep(DELAY_MS);
    return `Practice Questions for **${topicTitle}**:\n\n1. What are the primary characteristics of ${topicTitle}?\n2. How does ${topicTitle} apply in real-world scenarios?\n3. Can you compare and contrast the different approaches within ${topicTitle}?\n\n*Generated by mock GPT-4o.*`;
  },
  
  generateFlashcards: async (topicTitle) => {
    await sleep(DELAY_MS);
    return [
      { front: `What is the essence of ${topicTitle}?`, back: `It is a core foundational concept that builds the basis for advanced studies.` },
      { front: `Key formula or rule in ${topicTitle}?`, back: `Rule: Always double-check your initial assumptions.` },
      { front: `When was ${topicTitle} popularized?`, back: `It became widely adopted in modern educational frameworks.` }
    ];
  }
};
